package iad1tya.echo.music.ui.screens.settings

import androidx.compose.runtime.Composable
import androidx.compose.ui.res.stringResource
import iad1tya.echo.music.BuildConfig
import iad1tya.echo.music.R

data class SearchableSetting(
    val title: String,
    val description: String?,
    val category: String,
    val route: String
)

@Composable
fun getAllSearchableSettings(): List<SearchableSetting> {
    return listOf(
            Triple(stringResource(R.string.about), "About", "settings/about"),
            Triple(stringResource(R.string.account), "Account", "settings/account"),
            Triple(stringResource(R.string.action_exported), "Appearance", "settings/appearance"),
            Triple(stringResource(R.string.action_logout), "Account", "settings/account"),
            Triple(stringResource(R.string.advanced_login), "Account", "settings/account"),
            Triple(stringResource(R.string.ai_api_key), "AI Lyrics Translation", "settings/ai"),
            Triple(stringResource(R.string.ai_base_url), "AI Lyrics Translation", "settings/ai"),
            Triple(stringResource(R.string.ai_deepl_formality), "AI Lyrics Translation", "settings/ai"),
            Triple(stringResource(R.string.ai_deepl_formality_default), "AI Lyrics Translation", "settings/ai"),
            Triple(stringResource(R.string.ai_deepl_formality_less), "AI Lyrics Translation", "settings/ai"),
            Triple(stringResource(R.string.ai_deepl_formality_more), "AI Lyrics Translation", "settings/ai"),
            Triple(stringResource(R.string.ai_lyrics_translation), "AI Lyrics Translation", "settings/ai"),
            Triple(stringResource(R.string.ai_model), "AI Lyrics Translation", "settings/ai"),
            Triple(stringResource(R.string.ai_provider), "AI Lyrics Translation", "settings/ai"),
            Triple(stringResource(R.string.ai_provider_claude_help), "AI Lyrics Translation", "settings/ai"),
            Triple(stringResource(R.string.ai_provider_deepl_help), "AI Lyrics Translation", "settings/ai"),
            Triple(stringResource(R.string.ai_provider_gemini_help), "AI Lyrics Translation", "settings/ai"),
            Triple(stringResource(R.string.ai_provider_help), "AI Lyrics Translation", "settings/ai"),
            Triple(stringResource(R.string.ai_provider_mistral_help), "AI Lyrics Translation", "settings/ai"),
            Triple(stringResource(R.string.ai_provider_nvidia_help), "AI Lyrics Translation", "settings/ai"),
            Triple(stringResource(R.string.ai_provider_openai_help), "AI Lyrics Translation", "settings/ai"),
            Triple(stringResource(R.string.ai_provider_openrouter_help), "AI Lyrics Translation", "settings/ai"),
            Triple(stringResource(R.string.ai_provider_perplexity_help), "AI Lyrics Translation", "settings/ai"),
            Triple(stringResource(R.string.ai_provider_xai_help), "AI Lyrics Translation", "settings/ai"),
            Triple(stringResource(R.string.ai_setup_guide), "AI Lyrics Translation", "settings/ai"),
            Triple(stringResource(R.string.ai_target_language), "AI Lyrics Translation", "settings/ai"),
            Triple(stringResource(R.string.ai_translation_literal), "AI Lyrics Translation", "settings/ai"),
            Triple(stringResource(R.string.ai_translation_literal_desc), "AI Lyrics Translation", "settings/ai"),
            Triple(stringResource(R.string.ai_translation_mode), "AI Lyrics Translation", "settings/ai"),
            Triple(stringResource(R.string.ai_translation_transcribed), "AI Lyrics Translation", "settings/ai"),
            Triple(stringResource(R.string.ai_translation_transcribed_desc), "AI Lyrics Translation", "settings/ai"),
            Triple(stringResource(R.string.album_text), "Content", "settings/content"),
            Triple(stringResource(R.string.albums), "Appearance", "settings/appearance"),
            Triple(stringResource(R.string.app_language), "Content", "settings/content"),
            Triple(stringResource(R.string.app_update_uptodate), "System Update", "settings/update"),
            Triple(stringResource(R.string.app_updates_title), "System Update", "settings/update"),
            Triple(stringResource(R.string.appearance), "Appearance", "settings/appearance"),
            Triple(stringResource(R.string.apple_music), "Appearance", "settings/appearance"),
            Triple(stringResource(R.string.apple_music_lyrics_blur), "Appearance", "settings/appearance"),
            Triple(stringResource(R.string.apple_music_lyrics_blur_desc), "Appearance", "settings/appearance"),
            Triple(stringResource(R.string.apple_music_style), "Appearance", "settings/appearance"),
            Triple(stringResource(R.string.apple_music_style_letter), "Appearance", "settings/appearance"),
            Triple(stringResource(R.string.artist_page_settings), "Content", "settings/content"),
            Triple(stringResource(R.string.artists), "Appearance", "settings/appearance"),
            Triple(stringResource(R.string.audio_normalization), "Player and audio", "settings/player"),
            Triple(stringResource(R.string.audio_offload), "Player and audio", "settings/player"),
            Triple(stringResource(R.string.audio_offload_description), "Player and audio", "settings/player"),
            Triple(stringResource(R.string.audio_offload_disabled_by_crossfade), "Player and audio", "settings/player"),
            Triple(stringResource(R.string.audio_quality), "Player and audio", "settings/player"),
            Triple(stringResource(R.string.auto_download_on_like), "Player and audio", "settings/player"),
            Triple(stringResource(R.string.auto_download_on_like_desc), "Player and audio", "settings/player"),
            Triple(stringResource(R.string.auto_load_more), "Player and audio", "settings/player"),
            Triple(stringResource(R.string.auto_load_more_desc), "Player and audio", "settings/player"),
            Triple(stringResource(R.string.auto_playlists), "Appearance", "settings/appearance"),
            Triple(stringResource(R.string.auto_skip_next_on_error), "Player and audio", "settings/player"),
            Triple(stringResource(R.string.auto_skip_next_on_error_desc), "Player and audio", "settings/player"),
            Triple(stringResource(R.string.auto_update_check), "System Update", "settings/update"),
            Triple(stringResource(R.string.auto_update_check_subtitle), "System Update", "settings/update"),
            Triple(stringResource(R.string.backup_restore), "Backup & Restore", "settings/backup_restore"),
            Triple(stringResource(R.string.big), "Appearance", "settings/appearance"),
            Triple(stringResource(R.string.cache_size_warning_confirm), "Storage", "settings/storage"),
            Triple(stringResource(R.string.cache_size_warning_message), "Storage", "settings/storage"),
            Triple(stringResource(R.string.cache_size_warning_title), "Storage", "settings/storage"),
            Triple(stringResource(R.string.cd_back), "Appearance", "settings/appearance"),
            Triple(stringResource(R.string.cd_palette_item), "Appearance", "settings/appearance"),
            Triple(stringResource(R.string.center), "Appearance", "settings/appearance"),
            Triple(stringResource(R.string.clear_all_downloads), "Storage", "settings/storage"),
            Triple(stringResource(R.string.clear_downloaded_updates), "System Update", "settings/update"),
            Triple(stringResource(R.string.clear_downloaded_updates_desc), "System Update", "settings/update"),
            Triple(stringResource(R.string.clear_downloads_dialog), "Storage", "settings/storage"),
            Triple(stringResource(R.string.clear_image_cache), "Storage", "settings/storage"),
            Triple(stringResource(R.string.clear_image_cache_dialog), "Storage", "settings/storage"),
            Triple(stringResource(R.string.clear_listen_history), "Privacy", "settings/privacy"),
            Triple(stringResource(R.string.clear_listen_history_confirm), "Privacy", "settings/privacy"),
            Triple(stringResource(R.string.clear_search_history), "Privacy", "settings/privacy"),
            Triple(stringResource(R.string.clear_search_history_confirm), "Privacy", "settings/privacy"),
            Triple(stringResource(R.string.clear_song_cache), "Storage", "settings/storage"),
            Triple(stringResource(R.string.clear_song_cache_dialog), "Storage", "settings/storage"),
            Triple(stringResource(R.string.close), "Content", "settings/content"),
            Triple(stringResource(R.string.color_palette), "Appearance", "settings/appearance"),
            Triple(stringResource(R.string.commits), "System Update", "settings/update"),
            Triple(stringResource(R.string.config_proxy), "Content", "settings/content"),
            Triple(stringResource(R.string.content), "Content", "settings/content"),
            Triple(stringResource(R.string.content_country), "Content", "settings/content"),
            Triple(stringResource(R.string.content_language), "Content", "settings/content"),
            Triple(stringResource(R.string.crop_album_art), "Appearance", "settings/appearance"),
            Triple(stringResource(R.string.crop_album_art_desc), "Appearance", "settings/appearance"),
            Triple(stringResource(R.string.crossfade), "Player and audio", "settings/player"),
            Triple(stringResource(R.string.crossfade_beta_message), "Player and audio", "settings/player"),
            Triple(stringResource(R.string.crossfade_beta_title), "Player and audio", "settings/player"),
            Triple(stringResource(R.string.crossfade_desc), "Player and audio", "settings/player"),
            Triple(stringResource(R.string.crossfade_duration), "Player and audio", "settings/player"),
            Triple(stringResource(R.string.crossfade_gapless), "Player and audio", "settings/player"),
            Triple(stringResource(R.string.crossfade_gapless_desc), "Player and audio", "settings/player"),
            Triple(stringResource(R.string.dark_theme_follow_system), "Appearance", "settings/appearance"),
            Triple(stringResource(R.string.default_), "Appearance", "settings/appearance"),
            Triple(stringResource(R.string.default_lib_chips), "Appearance", "settings/appearance"),
            Triple(stringResource(R.string.default_open_tab), "Appearance", "settings/appearance"),
            Triple(stringResource(R.string.default_style), "Appearance", "settings/appearance"),
            Triple(stringResource(R.string.density_restart_message), "Appearance", "settings/appearance"),
            Triple(stringResource(R.string.disable), "Storage", "settings/storage"),
            Triple(stringResource(R.string.disable_load_more_when_repeat_all), "Player and audio", "settings/player"),
            Triple(stringResource(R.string.disable_load_more_when_repeat_all_desc), "Player and audio", "settings/player"),
            Triple(stringResource(R.string.disable_screenshot), "Privacy", "settings/privacy"),
            Triple(stringResource(R.string.disable_screenshot_desc), "Privacy", "settings/privacy"),
            Triple(stringResource(R.string.display_density), "Appearance", "settings/appearance"),
            Triple(stringResource(R.string.download_quality_title), "Player and audio", "settings/player"),
            Triple(stringResource(R.string.downloaded_songs), "Storage", "settings/storage"),
            Triple(stringResource(R.string.echo_equalizer), "Player and audio", "settings/player"),
            Triple(stringResource(R.string.echo_equalizer_desc), "Player and audio", "settings/player"),
            Triple(stringResource(R.string.nullmusic_1), "Appearance", "settings/appearance"),
            Triple(stringResource(R.string.nullmusic_canvas), "Appearance", "settings/appearance"),
            Triple(stringResource(R.string.nullmusic_canvas_desc), "Appearance", "settings/appearance"),
            Triple(stringResource(R.string.enable), "Player and audio", "settings/player"),
            Triple(stringResource(R.string.enable_authentication), "Content", "settings/content"),
            Triple(stringResource(R.string.enable_better_lyrics), "Content", "settings/content"),
            Triple(stringResource(R.string.enable_better_lyrics_desc), "Content", "settings/content"),
            Triple(stringResource(R.string.enable_dynamic_theme), "Appearance", "settings/appearance"),
            Triple(stringResource(R.string.enable_high_refresh_rate), "Appearance", "settings/appearance"),
            Triple(stringResource(R.string.enable_high_refresh_rate_desc), "Appearance", "settings/appearance"),
            Triple(stringResource(R.string.enable_kugou), "Content", "settings/content"),



            // Hardcoded Settings Missed by Generator

,
    )
}
